apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  annotations:
    harness.io/canary-weight: "{{ .Values.canary.weight }}"
    harness.io/canary-image: "{{ .Values.canary.image }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        canary: "{{ .Values.canary.enabled }}"
    spec:
      containers:
        - name: guestbook
          image: "{{ .Values.canary.image }}"
          ports:
            - containerPort: 80
